export type Language = "en" | "ar";

export type CurrencyCode = "AED" | "USD" | "EUR" | "GBP" | "SAR";

export const CURRENCIES: { code: CurrencyCode; rate: number }[] = [
  { code: "AED", rate: 1 },
  { code: "USD", rate: 0.2723 },
  { code: "EUR", rate: 0.2511 },
  { code: "GBP", rate: 0.213 },
  { code: "SAR", rate: 1.0206 },
];

export const DEFAULT_CURRENCY: CurrencyCode = "AED";
export const DEFAULT_LANGUAGE: Language = "en";

export const content = {
  en: {
    dir: "ltr",
    projectName: "Wadeem Gardens",
    tagline: "A New Standard of Luxury Living in Abu Dhabi",
    handover: "Q4 2030",
    status: "EOI Open",
    bedrooms: "4 - 6",
    paymentPlan: "25 / 75",
    currencies: {
      AED: { short: "AED", name: "UAE Dirham" },
      USD: { short: "USD", name: "US Dollar" },
      EUR: { short: "EUR", name: "Euro" },
      GBP: { short: "GBP", name: "British Pound" },
      SAR: { short: "SAR", name: "Saudi Riyal" },
    },
    brand: { eyebrow: "Abu Dhabi" },
    nav: {
      links: [
        { label: "About", href: "#about" },
        { label: "Amenities", href: "#amenities" },
        { label: "Payment Plan", href: "#payment" },
        { label: "Location", href: "#location" },
        { label: "Gallery", href: "#gallery" },
      ],
      register: "Register Interest",
      registerMobile: "Register My Interest",
      langCurrent: "English",
      langOther: "العربية",
      currency: "Currency",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      home: "Wadeem Gardens home",
      close: "Close",
    },
    hero: {
      eyebrow: "A New Address in Abu Dhabi",
      tagline: "A New Standard of Luxury Living in Abu Dhabi",
      from: "From",
      sub: "Premium 4-6 bedroom residences in the heart of Abu Dhabi, crafted for those who expect more from life.",
      ctaPrimary: "Register",
      ctaSecondary: "Download Brochure",
      metaStart: "Starting From",
      metaBedrooms: "Bedrooms",
      metaHandover: "Handover",
      scroll: "Scroll to Discover",
    },
    about: {
      eyebrow: "The Project",
      heading: "A New Chapter of Luxury Living",
      para1:
        "Wadeem Gardens is a landmark residential development set in one of Abu Dhabi's most coveted locations. Designed to the highest international standards, it brings together architectural excellence, uncompromising craftsmanship and a lifestyle defined by serenity and sophistication.",
      para2:
        "Set within the heart of the capital, the development offers a curated collection of premium residences that celebrate light, space and the surrounding landscape.",
      quote:
        "Architecture should speak of its time and place, but yearn for timelessness",
      facts: [
        { label: "Primary Use", value: "Residential" },
        { label: "Location", value: "Hudayriyat Island, Abu Dhabi" },
        { label: "Typologies", value: "4 - 6 Bedroom Villas" },
      ],
    },
    stats: {
      eyebrow: "Project Highlights",
      title: "Essential Facts at a Glance",
      labels: {
        starting: "Starting Price",
        bedrooms: "Bedrooms",
        payment: "Payment Plan",
        handover: "Handover",
        location: "Location",
        status: "Status",
      },
      subtitle:
        "bedroom residences available at",
      from: "from",
    },
    story: {
      eyebrow: "The Project",
      titleLine1: "The",
      titleLine2: "Project",
      title: "A Vision Realised in Every Detail",
      discoverMore: "Discover More",
      brief:
        "A landmark residential development in the heart of Abu Dhabi, blending architectural excellence, refined interiors and a serene, connected lifestyle.",
      items: [
        {
          label: "The Residences",
          heading: "Crafted for Distinction",
          description:
            "Every residence is a testament to refined living, where expansive floor plans meet meticulous attention to detail. Floor-to-ceiling windows frame breathtaking views, while premium finishes and thoughtful design create spaces that inspire.",
          imageLabel: "Interior Residences",
        },
        {
          label: "Architecture",
          heading: "Where Vision Meets Skyline",
          description:
            "A striking architectural statement that harmonizes with Abu Dhabi's iconic skyline. The design draws inspiration from the desert landscape and the Arabian Gulf, creating a landmark that is both timeless and contemporary.",
          imageLabel: "Architectural Design",
        },
        {
          label: "Landscape",
          heading: "Nature as Architecture",
          description:
            "Meticulously curated landscapes weave through the development, creating a seamless connection between indoor luxury and outdoor serenity. Lush gardens, reflective water features, and shaded walkways define the living experience.",
          imageLabel: "Landscaped Gardens",
        },
        {
          label: "Privacy",
          heading: "Your Sanctuary Above",
          description:
            "Designed with discretion and privacy at its core, each residence offers a secluded retreat from the world. Dedicated private entrances, sound-insulated walls, and expansive private terraces ensure an intimate living experience.",
          imageLabel: "Private Terrace",
        },
        {
          label: "Community",
          heading: "A World Within a World",
          description:
            "Beyond the private residences lies a vibrant community designed to foster connection. Shared spaces, social clubs, and curated events create a neighborhood where lasting relationships are built.",
          imageLabel: "Community Spaces",
        },
        {
          label: "Waterfront",
          heading: "Living by the Water",
          description:
            "Set along the pristine waterfront, the development offers an unparalleled connection to the sea. Private marina access, waterfront promenades, and stunning Arabian Gulf views redefine coastal luxury.",
          imageLabel: "Waterfront Living",
        },
      ],
    },
    propertyTypes: {
      eyebrow: "Property Types",
      title: "Residences Designed Around You",
      body: "A curated collection of villas, each tailored to a distinct way of living. Every residence is delivered with premium specifications and finishes.",
      startingFrom: "Starting From",
      explore: "Explore Residence",
      arabian: "Arabian",
      modern: "Modern",
      plotAreaLabel: "Plot Area",
      gsaLabel: "GSA (Built-Up Area)",
      footnote:
        "Prices are indicative starting prices for Wadeem Gardens. Final pricing and availability are subject to the developer.",
      cards: [
        {
          name: "4 Bedroom Villa",
          style: "Arabian / Modern",
          features: ["Arabian / Modern design", "Premium finishes", "Private driveway"],
        },
        {
          name: "5 Bedroom Villa",
          style: "Arabian / Modern",
          features: ["Arabian / Modern design", "Premium finishes", "Private driveway"],
        },
        {
          name: "6 Bedroom Villa",
          style: "Arabian / Modern",
          features: ["Arabian / Modern design", "Premium finishes", "Private driveway"],
        },
      ],
    },
    floorPlans: {
      eyebrow: "Floor Plans",
      title: "Designed to the Last Millimetre",
      body: "Explore the generous layouts of each residence. Plans are indicative and subject to final approval.",
      view: "View Plan",
    },
    amenities: {
      eyebrow: "Amenities",
      title: "Every Amenity Imagined",
      body: "A complete world of wellness, recreation and community, all within the privacy of your own address.",
      items: [
        "2.3 KM Airconditioned Spine",
        "Arena",
        "6 Clubhouses",
        "Office Park",
        "Healthcare Centres",
        "Waterfront Promenade",
        "Retail & Dining",
        "2 International Schools",
        "Cinemas",
      ],
    },
    payment: {
      eyebrow: "Payment Plan",
      title: "An Investment Structured Around You",
      planName: "First of its Kind Financial Solution",
      body1:
        "First of its Kind Financial Solution, co-branded with ADIB. Put down only",
      body2: "of the value while ADIB finances the remaining",
      stageLabels: [
        "Down Payment",
        "Construction Instalments",
        "Pre-Handover Finance",
        "Handover Payment",
        "Post-Handover Finance",
      ],
      details: [
        "On booking",
        "Months 8 / 14 / 20",
        "Before handover",
        "Month 48",
        "From month 54",
      ],
      payerBuyer: "Buyer",
      payerAdib: "ADIB",
      propertyPrice: "Property Price",
      selectPreset: "Select a residence to set the price",
      nationality: "Nationality",
      uaeNational: "UAE National",
      otherNationality: "Other Nationality",
      modonRebate: "Modon Rebate (UAE Nationals)",
      modonRebateHint: "5% rebate applied to your purchase amount",
      netOutOfPocket: "Net out of pocket",
      totalPrice: "Total Property Price",
      solution: "Financial Solution",
      withPartner: "With ADIB",
      buyerPocket: "Buyer out of pocket",
      financed: "ADIB financed",
      eoi: "Expression of Interest",
      eoiWindow: "EOI Window",
      eoiVip: "VIP Sales",
      eoiLaunch: "Sales Launch",
      eoiValue: "EOI Value",
      eoiNote:
        "Priority sales for ADIB pre-approved buyers with a previous EOI value of AED 50,000.",
      financedBy: "Financed by ADIB",
      summary: "You pay just",
      summary2: "of the value out of pocket",
      summary3: "ADIB finances the remaining",
      summary4: "across pre- and post-handover stages.",
      startingFrom: "Starting from",
      withHandover: "with handover",
      footnote:
        "Payment plan is indicative and subject to developer, ADIB and final terms. This calculator is for illustrative purposes only and does not constitute financial advice.",
    },
    location: {
      eyebrow: "Location",
      title: "Connected to Everything That Matters",
      body: "Positioned in one of Abu Dhabi's most sought-after destinations, Wadeem Gardens places the very best of the capital within effortless reach.",
      driveSuffix: " min",
      drive: "drive",
      masterLocation: "Master location",
      cityLine: "Hudayriyat Island, Abu Dhabi",
      places: [
        { place: "Downtown Abu Dhabi", minutes: 15 },
        { place: "Abu Dhabi International Airport", minutes: 20 },
        { place: "Yas Island", minutes: 10 },
        { place: "Saadiyat Island Cultural District", minutes: 12 },
        { place: "Al Maryah Island (Financial Centre)", minutes: 18 },
        { place: "Abu Dhabi Mall", minutes: 16 },
        { place: "Cleveland Clinic Abu Dhabi", minutes: 15 },
        { place: "British School Al Khubairat", minutes: 14 },
      ],
    },
    why: {
      eyebrow: "The Destination",
      title: "Why Abu Dhabi, Why Now",
      body: "Abu Dhabi has evolved into one of the world's most dynamic capital cities — a destination that pairs deep-rooted heritage with a vision for the future.",
      reasons: [
        {
          title: "Strategic Global Location",
          description:
            "Positioned at the crossroads of Europe, Asia and Africa, Abu Dhabi offers unparalleled global connectivity with direct flights to major world cities.",
        },
        {
          title: "World-Class Infrastructure",
          description:
            "From the award-winning airport to expanding metro networks and iconic cultural institutions, Abu Dhabi's infrastructure rivals any global capital.",
        },
        {
          title: "Unmatched Lifestyle",
          description: "Ferrari World, the Louvre Abu Dhabi, pristine beaches, desert adventures and year-round sunshine create an extraordinary quality of life.",
        },
        {
          title: "Growing Real Estate Demand",
          description:
            "Abu Dhabi's population growth and economic diversification continue to drive strong demand for premium residential properties.",
        },
        {
          title: "Waterfront Living Redefined",
          description:
            "Miles of pristine coastline, private beaches and marina access set Abu Dhabi apart as a premier waterfront living destination.",
        },
        {
          title: "Long-Term Value",
          description:
            "A stable economy, investor-friendly policies and limited premium supply make Abu Dhabi real estate a compelling long-term investment.",
        },
      ],
      ctaBox: {
        title: "A Destination Built for the Future",
        body: "Market dynamics, population growth and evolving preferences shape the property market. We encourage you to conduct independent due diligence on any investment.",
      },
      ctaLabel: "Request Investment Guide",
    },
    gallery: {
      eyebrow: "Gallery",
      title: "A Glimpse of What Awaits",
      body: "A first look at the residences, interiors and surroundings that define a new benchmark in Abu Dhabi living.",
      footer: "",
      scroll: "Scroll to explore",
      close: "Close gallery",
      prev: "Previous image",
      next: "Next image",
      itCaption: "Artist's impression",
      items: [
        "",
        "",
        "",
        "",
        "",
        "",
        "4 Bedroom Villa — Arabian",
        "4 Bedroom Villa — Modern",
        "5 Bedroom Villa — Arabian",
        "5 Bedroom Villa — Modern",
        "6 Bedroom Villa — Arabian",
        "6 Bedroom Villa — Modern",
      ],
    },
    brochure: {
      eyebrow: "Exclusive Launch",
      title: "Discover the Full Story",
      body: "Explore the residences, masterplan, amenities, payment plan and everything Wadeem Gardens has to offer.",
      cta: "Download Brochure",
      comingSoon: "Brochure Coming Soon",
      note: "The official project brochure will be available shortly.",
    },
    finalCta: {
      eyebrow: "Register Your Interest",
      title: "Make Your Move",
      body: "Register your interest to receive availability, pricing and launch updates for Wadeem Gardens.",
    },
    footer: {
      blurb: "A new standard of luxury living in Abu Dhabi. Premium residences, an uncompromising lifestyle and a landmark location.",
      explore: "Explore",
      getInTouch: "Get in Touch",
      register: "Register Interest",
      brochure: "Download Brochure",
      comingSoon: "Brochure Coming Soon",
      disclaimer:
        "Disclaimer: All information provided is subject to change and should be verified with the developer. Images, illustrations and renders are for representative purposes only. Prices, availability, specifications and payment plans are subject to change without prior notice. This website does not constitute an offer or contract.",
      privacy: "Privacy Policy",
      terms: "Terms of Use",
      cookies: "Cookie Policy",
      rights: "All rights reserved.",
      city: "Abu Dhabi",
      whatsapp: "WhatsApp",
    },
    form: {
      successTitle: "Thank You",
      successBody:
        "Your interest has been registered. Our team will be in touch with exclusive project details and availability.",
      fullName: "Full Name *",
      fullNamePh: "Your full name",
      email: "Email Address *",
      emailPh: "you@example.com",
      phone: "Phone Number *",
      phonePh: "+971 50 000 0000",
      country: "Country *",
      countryPh: "Select your country",
      propType: "Preferred Property Type *",
      propTypePh: "Select property type",
      budget: "Budget Range *",
      budgetPh: "Select budget range",
      message: "Message",
      messageOptional: "(optional)",
      messagePh: "Tell us anything about your requirements",
      consent:
        "I agree to be contacted about this project and accept the privacy policy. *",
      submit: "Register Interest",
      submitting: "Submitting...",
      errorMsg:
        "Something went wrong submitting your details. Please try again.",
      privacyNote:
        "We respect your privacy. Your information will only be used to contact you regarding this project.",
      heading: "Begin the Journey",
      description:
        "Share a few details and our team will be in touch with everything you need to know.",
      countries: [
        "United Arab Emirates",
        "Saudi Arabia",
        "United Kingdom",
        "United States",
        "India",
        "China",
        "Russia",
        "France",
        "Germany",
        "Italy",
        "Canada",
        "Australia",
        "Egypt",
        "Lebanon",
        "Pakistan",
        "Kuwait",
        "Qatar",
        "Bahrain",
        "Oman",
        "Other",
      ],
      propertyTypes: [
        "4 Bedroom Villa",
        "5 Bedroom Villa",
        "6 Bedroom Villa",
        "Undecided",
      ],
      budgets: [
        "AED 8.7M - 10.2M",
        "AED 10.2M - 11.6M",
        "AED 11.6M+",
        "Undecided",
      ],
      errFullName: "Please enter your full name",
      errEmail: "Please enter your email",
      errEmailInvalid: "Please enter a valid email address",
      errPhone: "Please enter your phone number",
      errPhoneInvalid: "Please enter a valid phone number",
      errCountry: "Please select your country",
      errPropType: "Please select a property type",
      errBudget: "Please select a budget range",
      errConsent: "Please accept the privacy notice to continue",
    },
    modal: {
      eyebrow: "New Launch",
      title: "Be Among the First to Discover",
      body: "Register your interest and receive exclusive project details, availability and the latest launch information.",
      cta: "Register My Interest",
      close: "Close dialog",
      email: "Email",
      phone: "Phone",
      message: "Message",
    },
    floating: {
      whatsapp: "Chat on WhatsApp",
      register: "Register Interest",
      backToTop: "Back to top",
      whatsappText:
        "Hello, I am interested in learning more about Wadeem Gardens in Abu Dhabi.",
      settings: "Language & Currency",
      language: "Language",
      currency: "Currency",
    },
    button: {
      explore: "Explore",
    },
  },
  ar: {
    dir: "rtl",
    projectName: "وديم جاردنز",
    tagline: "معيار جديد للحياة الفاخرة في أبوظبي",
    handover: "الربع الرابع 2030",
    status: "فتح التعبير عن الاهتمام",
    bedrooms: "4 - 6",
    paymentPlan: "25 / 75",
    currencies: {
      AED: { short: "AED", name: "درهم إماراتي" },
      USD: { short: "USD", name: "دولار أمريكي" },
      EUR: { short: "EUR", name: "يورو" },
      GBP: { short: "GBP", name: "جنيه إسترليني" },
      SAR: { short: "SAR", name: "ريال سعودي" },
    },
    brand: { eyebrow: "أبوظبي" },
    nav: {
      links: [
        { label: "نبذة", href: "#about" },
        { label: "المرافق", href: "#amenities" },
        { label: "خطة الدفع", href: "#payment" },
        { label: "الموقع", href: "#location" },
        { label: "المعرض", href: "#gallery" },
      ],
      register: "سجّل اهتمامك",
      registerMobile: "سجّل اهتمامي",
      langCurrent: "العربية",
      langOther: "English",
      currency: "العملة",
      openMenu: "فتح القائمة",
      closeMenu: "إغلاق القائمة",
      home: "الرئيسية - وديم جاردنز",
      close: "إغلاق",
    },
    hero: {
      eyebrow: "عنوان جديد في أبوظبي",
      tagline: "معيار جديد للحياة الفاخرة في أبوظبي",
      from: "تبدأ من",
      sub: "وحدات سكنية فاخرة من 4 إلى 6 غرف نوم في قلب أبوظبي، صُممت لمن يتطلعون إلى الأفضل في الحياة.",
      ctaPrimary: "سجّل",
      ctaSecondary: "تحميل البروشور",
      metaStart: "تبدأ من",
      metaBedrooms: "غرف النوم",
      metaHandover: "التسليم",
      scroll: "مرّر للاكتشاف",
    },
    about: {
      eyebrow: "المشروع",
      heading: "فصل جديد من الحياة الفاخرة",
      para1:
        "وديم جاردنز مشروع سكني بارز في إحدى أرقى المناطق بمدينة أبوظبي. صُمم وفق أعلى المعايير العالمية، ويجمع بين التميّز المعماري والحرفية الفائقة وأسلوب حياة يفيض صفاءً ورقيًّا.",
      para2:
        "يقدّم هذا التطوير، في قلب العاصمة، مجموعة مختارة بعناية من الوحدات الفاخرة التي تحتفي بالضوء والمساحات والطبيعة المحيطة.",
      quote:
        "العمارة يجب أن تتحرك على إيقاع زمانها ومكانها، مع أنها تطمح إلى الخلود",
      facts: [
        { label: "الاستخدام الأساسي", value: "سكني" },
        { label: "الموقع", value: "جزيرة الحديريات، أبوظبي" },
        { label: "الأنماط", value: "فلل من 4 إلى 6 غرف" },
      ],
    },
    stats: {
      eyebrow: "أبرز تفاصيل المشروع",
      title: "أهم المعلومات في لمحة",
      labels: {
        starting: "السعر المبدئي",
        bedrooms: "غرف النوم",
        payment: "خطة الدفع",
        handover: "التسليم",
        location: "الموقع",
        status: "الحالة",
      },
      subtitle: "وحدات سكنية متاحة تبدأ الأسعار من",
      from: "من",
    },
    story: {
      eyebrow: "المشروع",
      titleLine1: "عن",
      titleLine2: "المشروع",
      title: "رؤية تتجلى في أدق التفاصيل",
      discoverMore: "اكتشف المزيد",
      brief:
        "مشروع سكني في قلب أبوظبي، يجمع بين التميّز المعماري والتصميم الداخلي الراقي وأسلوب حياة هادئ ومترابط.",
      items: [
        {
          label: "الوحدات السكنية",
          heading: "صياغة تتسم بالتميّز",
          description:
            "كل وحدة سكنية تمثل ارتقاءً بمعايير العيش، حيث تلتقي المساحات الواسعة مع دقة التفاصيل. نوافذ تمتد من الأرض إلى السقف تطل على مناظر خلابة، فيما تقدّم التشطيبات الفاخرة والتصميم المتوائم مساحات تبعث على الإلهام.",
          imageLabel: "وحدات داخلية",
        },
        {
          label: "العمارة",
          heading: "حيث تلتقي الرؤية مع الأفق",
          description:
            "بيان معماري لافت ينسجم مع أفق أبوظبي المميز. استلهم التصميم من المناظر الصحراوية ومن الخليج العربي، ليمثل معلماً يمتزج فيه الخلود بالعصرية.",
          imageLabel: "التصميم المعماري",
        },
        {
          label: "التنسيق",
          heading: "الطبيعة كعمارة",
          description:
            "تنسيقات طبيعية مدروسة تمتد عبر المشروع لتربط الفخامة الداخلية بالهدوء الخارجي. حدائق وافرة ومسطحات مائية عاكسة وممرات مظللة ترسم تجربة عيش متكاملة.",
          imageLabel: "حدائق مصممة",
        },
        {
          label: "الخصوصية",
          heading: "ملاذك الخاص في الأعالي",
          description:
            "صُمم مشروعنا على أسس من التقدير والخصوصية، إذ تمنح كل وحدة سكنية ملاذاً منزوياً عن العالم. مداخل خاصة ومواد عازلة للصوت وتراسات واسعة تضمن تجربة عيش حميمية.",
          imageLabel: "تراس خاص",
        },
        {
          label: "المجتمع",
          heading: "عالمٌ ضمن عالم",
          description:
            "إلى جانب الوحدات السكنية الخاصة، يحتضن المشروع مجتمعاً نابضاً بالحياة يسهم في تعزيز التواصل. مساحات مشتركة وأندية اجتماعية وفعاليات منتقاة تصنع حيّاً تُبنى فيه علاقات تدوم.",
          imageLabel: "مساحات مجتمعية",
        },
        {
          label: "الواجهة المائية",
          heading: "عيشٌ على ضفاف الماء",
          description:
            "على ضفاف الواجهة المائية البكر، يقدّم المشروع صلة متكاملة بالبحر. مرسى خاص وممشى مائي وإطلالات ساحرة على الخليج العربي تعيد تعريف الفخامة الساحلية.",
          imageLabel: "الحياة على الواجهة المائية",
        },
      ],
    },
    propertyTypes: {
      eyebrow: "أنماط الوحدات",
      title: "وحدات صُممت لتناسبك",
      body: "مجموعة مختارة من الفلل، صُممت كلٌّ منها لأسلوب حياة مختلف. جميع الوحدات تُسلَّم بمواصفات وتشطيبات فاخرة.",
      startingFrom: "تبدأ من",
      explore: "استكشف الوحدة",
      arabian: "عربي",
      modern: "حديث",
      plotAreaLabel: "مساحة الأرض",
      gsaLabel: "المساحة العامة (GSA)",
      footnote:
        "الأسعار مبدئية استرشادية لمشروع وديم جاردنز. السعر النهائي والتوفر يعتمدان على المطور.",
      cards: [
        {
          name: "فيلا 4 غرف نوم",
          style: "ستايل عربي / حديث",
          features: ["تصميم عربي / حديث", "تشطيبات فاخرة", "مواقف خاصة"],
        },
        {
          name: "فيلا 5 غرف نوم",
          style: "ستايل عربي / حديث",
          features: ["تصميم عربي / حديث", "تشطيبات فاخرة", "مواقف خاصة"],
        },
        {
          name: "فيلا 6 غرف نوم",
          style: "ستايل عربي / حديث",
          features: ["تصميم عربي / حديث", "تشطيبات فاخرة", "مواقف خاصة"],
        },
      ],
    },
    floorPlans: {
      eyebrow: "المخططات",
      title: "تصميم حتى أدق التفاصيل",
      body: "استكشف المساحات الواسعة لكل فيلا. المخططات استرشادية وقابلة للتعديل وفق الموافقات النهائية.",
      view: "عرض المخطط",
    },
    amenities: {
      eyebrow: "المرافق",
      title: "كل المرافق التي تحتاجها",
      body: "عالم متكامل من الصحة والترفيه والمجتمع، ضمن خصوصية عنوانك الخاص.",
      items: [
        "ممر مكيف بطول 2.3 كم",
        "مساحة للتواصل",
        "6 نوادٍ مجتمعية",
        "مجمّع المكاتب",
        "مراكز رعاية صحية",
        "ممشى على الواجهة المائية",
        "تجزئة ومطاعم",
        "مدرستان دوليتان",
        "سينما",
      ],
    },
    payment: {
      eyebrow: "خطة الدفع",
      title: "استثمار صُمم ليكون في صالحك",
      planName: "حل مالي فريد من نوعه",
      body1:
        "حل مالي فريد من نوعه بالشراكة مع ADIB. تدفع",
      body2: "من قيمة العقار بينما يمول ADIB النسبة المتبقية البالغة",
      stageLabels: [
        "الدفعة المقدمة",
        "أقساط الإنشاء",
        "تمويل ما قبل التسليم",
        "دفعة التسليم",
        "تمويل ما بعد التسليم",
      ],
      details: [
        "عند الحجز",
        "الأشهر 8 / 14 / 20",
        "قبل التسليم",
        "الشهر 48",
        "ابتداءً من الشهر 54",
      ],
      payerBuyer: "المشتري",
      payerAdib: "ADIB",
      propertyPrice: "سعر العقار",
      selectPreset: "اختر وحدة لتحديد السعر",
      nationality: "الجنسية",
      uaeNational: "مواطن إماراتي",
      otherNationality: "جنسية أخرى",
      modonRebate: "خصم مدن (المواطنون الإماراتيون)",
      modonRebateHint: "خصم 5% يُطبق على قيمة الشراء",
      netOutOfPocket: "صافي الدفع",
      totalPrice: "السعر الإجمالي للعقار",
      solution: "الحل المالي",
      withPartner: "بالشراكة مع ADIB",
      buyerPocket: "ما يدفعه المشتري",
      financed: "تمويل ADIB",
      eoi: "التعبير عن الاهتمام",
      eoiWindow: "فترة التعبير عن الاهتمام",
      eoiVip: "مبيعات VIP",
      eoiLaunch: "الانطلاق الرسمي للمبيعات",
      eoiValue: "قيمة التعبير عن الاهتمام",
      eoiNote:
        "أولوية البيع للمشترين المعتمدين لدى ADIB ممن سبق أن قدّموا تعبير اهتمام بقيمة 50,000 درهم.",
      financedBy: "تمويل ADIB",
      summary: "تدفع فقط",
      summary2: "من قيمة العقار من جيبك الخاص",
      summary3: "بينما يمول ADIB النسبة الباقية",
      summary4: "عبر مراحل ما قبل وما بعد التسليم.",
      startingFrom: "تبدأ من",
      withHandover: "والتسليم",
      footnote:
        "خطة الدفع استرشادية وتخضع للشروط النهائية للمطور وADIB. هذه الحاسبة لأغراض توضيحية فقط ولا تمثل استشارة مالية.",
    },
    location: {
      eyebrow: "الموقع",
      title: "قريبًا من كل ما يهمّك",
      body: "في إحدى الوجهات المرغوبة في أبوظبي، يضع وديم جاردنز أجمل ما تقدمه العاصمة على بعد خطوات.",
      driveSuffix: " دقيقة",
      drive: "بالسيارة",
      masterLocation: "الموقع الرئيسي",
      cityLine: "جزيرة الحديريات، أبوظبي",
      places: [
        { place: "وسط مدينة أبوظبي", minutes: 15 },
        { place: "مطار أبوظبي الدولي", minutes: 20 },
        { place: "جزيرة ياس", minutes: 10 },
        { place: "الحي الثقافي في جزيرة السعديات", minutes: 12 },
        { place: "جزيرة المارية (المركز المالي)", minutes: 18 },
        { place: "أبوظبي مول", minutes: 16 },
        { place: "مدينة كليفلاند كلينك أبوظبي", minutes: 15 },
        { place: "المدرسة البريطانية بالخبيرات", minutes: 14 },
      ],
    },
    why: {
      eyebrow: "الوجهة",
      title: "لماذا أبوظبي، ولماذا الآن",
      body: "تطوّرت أبوظبي لتصبح واحدة من أكثر العواصم ديناميكية في العالم — وجهة تجمع بين الجذور الراسخة ورؤية مستقبلية طموحة.",
      reasons: [
        {
          title: "موقع استراتيجي عالمي",
          description:
            "على مفترق طرق أوروبا وآسيا وأفريقيا، تقدّم أبوظبي إمكانات اتصال عالمية فائقة مع رحلات مباشرة إلى كبرى مدن العالم.",
        },
        {
          title: "بنية تحتية عالمية",
          description:
            "من المطار الحائز على جوائز إلى الشبكات المترو الموسعة والمؤسسات الثقافية الأيقونية، تنافس بنية أبوظبي التحتية أيَ عاصمة عالمية.",
        },
        {
          title: "أسلوب حياة لا يُضاهى",
          description:
            "فيراري وورلد ولوفر أبوظبي وشواطئ نقية ومغامرات في الصحراء وشمس على مدار العام تصنع جودة حياة استثنائية.",
        },
        {
          title: "طلب عقاري متنامٍ",
          description:
            "النمو السكاني والتنوع الاقتصادي في أبوظبي يواصلان تعزيز الطلب على الوحدات السكنية الفاخرة.",
        },
        {
          title: "إعادة تعريف الحياة على الواجهة المائية",
          description:
            "كيلومترات من السواحل البكر والشواطئ الخاصة ووصول إلى المراسي تميّز أبوظبي كوجهة رائدة للحياة على الماء.",
        },
        {
          title: "قيمة طويلة الأجل",
          description:
            "اقتصاد مستقر وسياسات مشجعة للمستثمرين وعرض محدود من الوحدات الفاخرة يجعلان عقارات أبوظبي استثمارًا طويل الأمد واعدًا.",
        },
      ],
      ctaBox: {
        title: "وجهة بُنيت للمستقبل",
        body: "تشكّل ديناميكيات السوق والنمو السكاني وتغيّر التفضيلات السوق العقاري. نشجعك على إجراء بحث مستقل قبل اتخاذ أي قرار استثماري.",
      },
      ctaLabel: "اطلب دليل الاستثمار",
    },
    gallery: {
      eyebrow: "المعرض",
      title: "لمحة عمّا ينتظرك",
      body: "نظرة أولى على الوحدات والديكورات الداخلية والمحيط الذي يرسم معيارًا جديدًا للحياة في أبوظبي.",
      footer: "",
      scroll: "مرّر للاستكشاف",
      close: "إغلاق المعرض",
      prev: "الصورة السابقة",
      next: "الصورة التالية",
      itCaption: "انطباع فني",
      items: [
        "",
        "",
        "",
        "",
        "",
        "",
        "فيلا 4 غرف — عربي",
        "فيلا 4 غرف — حديث",
        "فيلا 5 غرف — عربي",
        "فيلا 5 غرف — حديث",
        "فيلا 6 غرف — عربي",
        "فيلا 6 غرف — حديث",
      ],
    },
    brochure: {
      eyebrow: "إطلاق حصري",
      title: "اكتشف القصة كاملة",
      body: "استكشف الوحدات والمخطط العام والمرافق وخطة الدفع وكل ما تقدمه وديم جاردنز.",
      cta: "تحميل البروشور",
      comingSoon: "البروشور قريبًا",
      note: "سيتوفر البروشور الرسمي للمشروع قريبًا.",
    },
    finalCta: {
      eyebrow: "سجّل اهتمامك",
      title: "ابدأ الخطوة القادمة",
      body: "سجّل اهتمامك ليصلك التوفر والأسعار وآخر تحديثات الإطلاق لمشروع وديم جاردنز.",
    },
    footer: {
      blurb: "معيار جديد للحياة الفاخرة في أبوظبي. وحدات فاخرة وموقع بارز، وأسلوب حياة لا يمسّه المساومة.",
      explore: "استكشف",
      getInTouch: "تواصل معنا",
      register: "سجّل اهتمامك",
      brochure: "تحميل البروشور",
      comingSoon: "البروشور قريبًا",
      disclaimer:
        "إخلاء مسؤولية: جميع المعلومات المعروضة قابلة للتغيير ويتعين التحقق منها لدى المطور. الصور والرسوم والنماذج العرضية لأغراض توضيحية فقط. الأسعار والتوفر والمواصفات وخطط الدفع قابلة للتغيير دون إشعار مسبق. هذا الموقع لا يشكل عرضًا أو عقدًا.",
      privacy: "سياسة الخصوصية",
      terms: "شروط الاستخدام",
      cookies: "سياسة ملفات الارتباط",
      rights: "جميع الحقوق محفوظة.",
      city: "أبوظبي",
      whatsapp: "واتساب",
    },
    form: {
      successTitle: "شكرًا لك",
      successBody:
        "تم تسجيل اهتمامك. سيتواصل معك فريقنا بتفاصيل المشروع الحصرية والتوفر.",
      fullName: "الاسم الكامل *",
      fullNamePh: "اسمك الكامل",
      email: "البريد الإلكتروني *",
      emailPh: "you@example.com",
      phone: "رقم الهاتف *",
      phonePh: "+971 50 000 0000",
      country: "الدولة *",
      countryPh: "اختر دولتك",
      propType: "نوع العقار المفضل *",
      propTypePh: "اختر نوع العقار",
      budget: "الميزانية المفضلة *",
      budgetPh: "اختر الميزانية المفضلة",
      message: "رسالة",
      messageOptional: "(اختياري)",
      messagePh: "أخبرنا عن متطلباتك",
      consent:
        "أوافق على تواصلكم معي بشأن هذا المشروع وأقبل سياسة الخصوصية. *",
      submit: "سجّل اهتمامك",
      submitting: "جارٍ الإرسال...",
      errorMsg: "حدث خطأ أثناء إرسال بياناتك. يرجى المحاولة مرة أخرى.",
      privacyNote:
        "نحترم خصوصيتك. سيتم استخدام معلوماتك فقط للتواصل معك بخصوص هذا المشروع.",
      heading: "ابدأ الرحلة",
      description:
        "شاركنا ببعض التفاصيل وسيتواصل معك فريقنا بكل ما تحتاج معرفته.",
      countries: [
        "الإمارات العربية المتحدة",
        "المملكة العربية السعودية",
        "المملكة المتحدة",
        "الولايات المتحدة الأمريكية",
        "الهند",
        "الصين",
        "روسيا",
        "فرنسا",
        "ألمانيا",
        "إيطاليا",
        "كندا",
        "أستراليا",
        "مصر",
        "لبنان",
        "باكستان",
        "الكويت",
        "قطر",
        "البحرين",
        "عُمان",
        "أخرى",
      ],
      propertyTypes: [
        "فيلا 4 غرف نوم",
        "فيلا 5 غرف نوم",
        "فيلا 6 غرف نوم",
        "غير محدد",
      ],
      budgets: [
        "8.7 - 10.2 مليون درهم",
        "10.2 - 11.6 مليون درهم",
        "+11.6 مليون درهم",
        "غير محدد",
      ],
      errFullName: "الرجاء إدخال اسمك الكامل",
      errEmail: "الرجاء إدخال بريدك الإلكتروني",
      errEmailInvalid: "الرجاء إدخال بريد إلكتروني صحيح",
      errPhone: "الرجاء إدخال رقم هاتفك",
      errPhoneInvalid: "الرجاء إدخال رقم هاتف صحيح",
      errCountry: "الرجاء اختيار دولتك",
      errPropType: "الرجاء اختيار نوع العقار",
      errBudget: "الرجاء اختيار الميزانية المفضلة",
      errConsent: "الرجاء قبول إشعار الخصوصية للمتابعة",
    },
    modal: {
      eyebrow: "طرح جديد",
      title: "كن من أوائل من يكتشف",
      body: "سجّل اهتمامك واستلم تفاصيل المشروع الحصرية والتوفر وآخر أخبار الإطلاق.",
      cta: "سجّل اهتمامي",
      close: "إغلاق النافذة",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      message: "الرسالة",
    },
    floating: {
      whatsapp: "الدردشة عبر واتساب",
      register: "سجّل اهتمامك",
      backToTop: "العودة للأعلى",
      whatsappText:
        "مرحبًا، أنا مهتم بمعرفة المزيد عن وديم جاردنز في أبوظبي.",
      settings: "اللغة والعملة",
      language: "اللغة",
      currency: "العملة",
    },
    button: {
      explore: "استكشف",
    },
  },
};

export type Content = (typeof content)["en"];